teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1 # Left thumb stick vertical
      y: 0 # Left thumb stick horizontal
    scale_linear:
      x: 1.0
      y: 1.0

    axis_angular:
      yaw: 3 # Right thumb stick horizontal
      pitch: 4
    scale_angular:
      yaw: 1.0
      pitch: 1.0

    enable_button: 5 # Right trigger button
    require_enable_button: false
